import os
import re

# Dictionnaire : numéro article → meta description
DESCRIPTIONS = {
    201: "Acheter sa résidence principale : le guide 2025 — Le bon moment pour acheter. Guide complet sur Economya.fr",
    202: "Renégocier son crédit immobilier — Jusqu'à 20 000€ économisés. Guide complet sur Economya.fr",
    203: "PTZ 2025 : conditions, simulation, communes éligibles — Jusqu'à 100 000€ sans intérêts. Guide complet sur Economya.fr",
    204: "Frais de notaire : comment les calculer exactement — Évitez les mauvaises surprises. Guide complet sur Economya.fr",
    205: "Dépôt de garantie : récupérer sa caution — Récupérez chaque centime. Guide complet sur Economya.fr",
    206: "Rénovation énergétique : toutes les aides 2025 — Jusqu'à 90% des travaux financés. Guide complet sur Economya.fr",
    207: "Investir en LMNP : guide complet — Rendement 5–7% net. Guide complet sur Economya.fr",
    208: "Charges de copropriété : comment les contester — Réduisez vos charges. Guide complet sur Economya.fr",
    209: "Home staging : valoriser son bien pour vendre — +10% sur le prix de vente. Guide complet sur Economya.fr",
    210: "Bail locatif : droits et obligations du locataire — Protégez-vous juridiquement. Guide complet sur Economya.fr",
    211: "Construction maison : éviter les arnaques — Économisez 30 000€. Guide complet sur Economya.fr",
    212: "Diagnostics immobiliers : lesquels sont obligatoires — Ne payez pas l'inutile. Guide complet sur Economya.fr",
    213: "Viager : comment ça marche vraiment — Acheter à 30–50% de décote. Guide complet sur Economya.fr",
    214: "Bail en colocation : rédiger un contrat solide soi-même — Loyer divisé par 2 ou 3. Guide complet sur Economya.fr",
    215: "SCI familiale : créer et gérer — Optimisez la transmission. Guide complet sur Economya.fr",
    216: "Bulletin de salaire : décrypter chaque ligne — Comprendre ce qu'on vous prend. Guide complet sur Economya.fr",
    217: "Négocier son salaire : scripts qui marchent — +2 000 à +5 000€/an. Guide complet sur Economya.fr",
    218: "Chômage ARE : calculer ses droits en 2025 — Jusqu'à 75% du salaire. Guide complet sur Economya.fr",
    219: "Rupture conventionnelle : tout ce qu'il faut savoir — Négociez chaque euro. Guide complet sur Economya.fr",
    220: "Démissionner pour reconversion : droits au chômage — Partir sans perdre ses droits. Guide complet sur Economya.fr",
    221: "Arrêt maladie : ce que touche vraiment le salarié — Compléments et prévoyance. Guide complet sur Economya.fr",
    222: "Télétravail : droits, indemnités, équipement — Déduisez vos frais. Guide complet sur Economya.fr",
    223: "Prime de partage de la valeur 2025 — Jusqu'à 6 000€ exonérés. Guide complet sur Economya.fr",
    224: "Intéressement et participation : optimiser — Défiscalisez vos primes. Guide complet sur Economya.fr",
    225: "PEE et PERCO : utiliser au mieux — Abondement employeur. Guide complet sur Economya.fr",
    226: "Heures supplémentaires : calcul et récupération — Ne laissez rien passer. Guide complet sur Economya.fr",
    227: "Portage salarial : avantages et inconvénients — Indépendant avec filet. Guide complet sur Economya.fr",
    228: "CDD : droits et prime de précarité — 10% en fin de contrat. Guide complet sur Economya.fr",
    229: "Reconversion professionnelle : financer sa formation — CPF, OPCO et aides. Guide complet sur Economya.fr",
    230: "Primes non imposables : ce qu'on peut verser — Optimisez votre net. Guide complet sur Economya.fr",
    231: "100% Santé : ce qui est vraiment remboursé — 0€ de reste à charge. Guide complet sur Economya.fr",
    232: "ALD : droits, prise en charge à 100% — Soins entièrement remboursés. Guide complet sur Economya.fr",
    233: "Complémentaire santé solidaire (CSS) gratuite — Mutuelle gratuite ou 1€/jour. Guide complet sur Economya.fr",
    234: "Remboursement lunettes : toutes les aides — Lunettes à 0€ possibles. Guide complet sur Economya.fr",
    235: "Soins dentaires : réduire la facture — Jusqu'à 70% remboursé. Guide complet sur Economya.fr",
    236: "Médicaments génériques : économiser à l'officine — Jusqu'à -70% sur les médicaments. Guide complet sur Economya.fr",
    237: "Téléconsultation médicale gratuite — Consulter sans avancer de frais. Guide complet sur Economya.fr",
    238: "Allocation adulte handicapé (AAH) 2025 — Jusqu'à 1 016€/mois. Guide complet sur Economya.fr",
    239: "Reste à charge zéro : guide pratique — Soins sans débourser un centime. Guide complet sur Economya.fr",
    240: "Aide à domicile : les aides financières — APA et PCH décryptées. Guide complet sur Economya.fr",
    241: "PUMA : protection universelle maladie — Droits automatiques à la Sécu. Guide complet sur Economya.fr",
    242: "Hospitalisation : éviter les frais cachés — Chambre particulière remboursée. Guide complet sur Economya.fr",
    243: "Médecine douce remboursée par la mutuelle — Ostéo, acupuncture pris en charge. Guide complet sur Economya.fr",
    244: "Soins transfrontaliers : se faire soigner moins cher — Belgique, Espagne, moins cher. Guide complet sur Economya.fr",
    245: "Don d'organes : ce qu'il faut savoir — Guide complet. Guide complet sur Economya.fr",
    246: "ChatGPT gratuit : tout ce qu'on peut faire en 2025 — IA gratuite au quotidien. Guide complet sur Economya.fr",
    247: "IA pour économiser au quotidien : les meilleurs outils — Automatisez vos économies. Guide complet sur Economya.fr",
    248: "Smartphone reconditionné : le comparatif complet — iPhone à partir de 200€. Guide complet sur Economya.fr",
    249: "Forfait 5G pas cher : comparatif opérateurs — 5G dès 6€/mois. Guide complet sur Economya.fr",
    250: "VPN : gratuit ou payant, lequel choisir — Protégez-vous gratuitement. Guide complet sur Economya.fr",
    251: "Antivirus gratuit : les meilleurs en 2025 — Protection sans abonnement. Guide complet sur Economya.fr",
    252: "Netflix 2025 : partage de compte, règles, prix — Compte légal dès 4,99€/mois. Guide complet sur Economya.fr",
    253: "Applications de budget : les meilleures gratuites — Gérez vos finances en 5 min. Guide complet sur Economya.fr",
    254: "IA pour rédiger son CV : outils et méthode — CV parfait gratuitement. Guide complet sur Economya.fr",
    255: "MacBook, ThinkPad, Dell : quel PC reconditionné choisir — PC performant dès 250€. Guide complet sur Economya.fr",
    256: "Cloud gratuit : comparer les offres — 15 à 100 Go gratuits. Guide complet sur Economya.fr",
    257: "Désabonnement et résiliation : outils gratuits — Économisez en 2 clics. Guide complet sur Economya.fr",
    258: "Deepseek, Mistral, Gemini : quel IA gratuit choisir — Le meilleur IA selon vos besoins. Guide complet sur Economya.fr",
    259: "Piratage informatique : se protéger gratuitement — Évitez les arnaques coûteuses. Guide complet sur Economya.fr",
    260: "Données personnelles : les récupérer et les protéger — Votre vie privée a de la valeur. Guide complet sur Economya.fr",
    261: "Bonus écologique 2025 : montants et conditions — Jusqu'à 7 000€ de bonus. Guide complet sur Economya.fr",
    262: "Assurance auto : comparer et économiser — Jusqu'à 400€ économisés/an. Guide complet sur Economya.fr",
    263: "Malus écologique 2025 : barème complet — Évitez jusqu'à 60 000€ de malus. Guide complet sur Economya.fr",
    264: "Permis de conduire moins cher : toutes les options — Permis dès 800€. Guide complet sur Economya.fr",
    265: "Train pas cher : cartes SNCF et astuces 2025 — -50% sur chaque billet. Guide complet sur Economya.fr",
    266: "Leasing social VE 2025 : conditions et dossier — VE dès 100€/mois. Guide complet sur Economya.fr",
    267: "Covoiturage domicile-travail : aides et déduction — Jusqu'à 3 000€/an défiscalisés. Guide complet sur Economya.fr",
    268: "Location longue durée vs achat : que choisir — Le vrai calcul. Guide complet sur Economya.fr",
    269: "Contester une amende : procédure complète — 50% des recours aboutissent. Guide complet sur Economya.fr",
    270: "Vignette Crit'Air : tout savoir — Évitez les amendes de 135€. Guide complet sur Economya.fr",
    271: "Carburant : où trouver le moins cher — Jusqu'à 15 centimes de moins/litre. Guide complet sur Economya.fr",
    272: "Vélo cargo électrique : aides à l'achat — Jusqu'à 2 000€ de subvention. Guide complet sur Economya.fr",
    273: "Contrôle technique : points clés et coûts — Préparez votre voiture. Guide complet sur Economya.fr",
    274: "Péages : comment les éviter légalement — Des centaines économisés/an. Guide complet sur Economya.fr",
    275: "Pneus : quand les changer et où acheter moins cher — -40% en commandant en ligne. Guide complet sur Economya.fr",
    276: "Flying Blue, Miles&More : programmes fidélité décryptés — Vols gratuits avec vos points. Guide complet sur Economya.fr",
    277: "Interrail 2025 : guide complet Europe en train — Europe entière dès 209€. Guide complet sur Economya.fr",
    278: "Airbnb vs hôtel : que choisir selon les cas — Jusqu'à -50% sur l'hébergement. Guide complet sur Economya.fr",
    279: "Bagages cabine seulement : le guide ultime — Économisez 50–120€ par vol. Guide complet sur Economya.fr",
    280: "Voyager en famille pour moins de 2 000€ — 4 personnes, vrai budget. Guide complet sur Economya.fr",
    281: "Travel hacking France : meilleures cartes bancaires — Voyages offerts par votre banque. Guide complet sur Economya.fr",
    282: "Vacances hors saison : destinations et économies — -40% en mai ou septembre. Guide complet sur Economya.fr",
    283: "Slow travel : voyager moins cher en restant plus — Coût journalier divisé par 2. Guide complet sur Economya.fr",
    284: "Croisière pas chère : les vraies astuces — Croisière dès 400€/pers.. Guide complet sur Economya.fr",
    285: "Échange de maison : comment ça marche — Hébergement gratuit partout. Guide complet sur Economya.fr",
    286: "Camping en France : atlas des sites gratuits — Nuits gratuites en pleine nature. Guide complet sur Economya.fr",
    287: "Visa working holiday : Australie, Canada, Nouvelle-Zélande — Voyager et travailler 2 ans. Guide complet sur Economya.fr",
    288: "Financer un tour du monde : méthode réaliste — Tour du monde dès 12 000€. Guide complet sur Economya.fr",
    289: "Étudier à l'étranger moins cher qu'en France — Master gratuit en Europe. Guide complet sur Economya.fr",
    290: "Assurance voyage : quand est-elle vraiment utile — Couvrez-vous sans sur-payer. Guide complet sur Economya.fr",
    291: "Zéro gaspillage alimentaire : méthode complète — 400€ économisés/an. Guide complet sur Economya.fr",
    292: "Manger équilibré à petit budget — Repas complet à 2€. Guide complet sur Economya.fr",
    293: "Congélation : tout ce qu'on peut congeler — Zéro gaspillage au congélateur. Guide complet sur Economya.fr",
    294: "DLC vs DLUO : dates de péremption expliquées — Arrêtez de jeter trop tôt. Guide complet sur Economya.fr",
    295: "Manger vegan pas cher : menu de la semaine — 1€/repas, c'est possible. Guide complet sur Economya.fr",
    296: "Alimentation anti-inflammatoire pas chère — Santé sans supplément à 40€. Guide complet sur Economya.fr",
    297: "Légumes et fruits de saison : calendrier et prix — -50% hors saison vs en saison. Guide complet sur Economya.fr",
    298: "Cuisiner pour les intolérants sans se ruiner — Sans gluten, sans lactose, pas cher. Guide complet sur Economya.fr",
    299: "Boissons fermentées maison : kéfir, kombucha — 0,10€ par litre. Guide complet sur Economya.fr",
    300: "Faire son beurre, yaourt et fromage frais maison — 3× moins cher qu'en magasin. Guide complet sur Economya.fr",
    301: "Anti-gaspi apps : les meilleures en 2025 — Repas à -70% avec Too Good To Go. Guide complet sur Economya.fr",
    302: "Menus semaine à 30€ : idées et recettes — 5 repas pour 4 à 1,50€/pers.. Guide complet sur Economya.fr",
    303: "Boîtes de conserve : recettes rapides et économiques — Repas complet à 0,80€. Guide complet sur Economya.fr",
    304: "AMAP : rejoindre et économiser — Bio local à -30%. Guide complet sur Economya.fr",
    305: "Cuisiner sans four : équipements alternatifs — Économisez sur l'énergie. Guide complet sur Economya.fr",
    306: "Allocations familiales 2025 : montants et conditions — Jusqu'à 350€/mois. Guide complet sur Economya.fr",
    307: "Prime naissance CAF : toutes les aides — Jusqu'à 1 000€ à la naissance. Guide complet sur Economya.fr",
    308: "Congé parental : droits et allocations — PreParE jusqu'à 600€/mois. Guide complet sur Economya.fr",
    309: "Fournitures scolaires pas chères : le guide — Rentrée complète pour 30€. Guide complet sur Economya.fr",
    310: "Activités enfants gratuites ou à petit prix — Weekend enfants à 0€. Guide complet sur Economya.fr",
    311: "Colonies de vacances CAF : financement — Colo payée à 80% par la CAF. Guide complet sur Economya.fr",
    312: "Vêtements enfants pas chers : meilleures sources — Vinted, tailles dessus. Guide complet sur Economya.fr",
    313: "Anniversaire enfant : organiser pour moins de 50€ — Fête réussie à petit prix. Guide complet sur Economya.fr",
    314: "Chambre bébé complète à petit budget — Tout pour 300€ max. Guide complet sur Economya.fr",
    315: "Garde alternée : impact sur les aides sociales — Optimisez vos droits. Guide complet sur Economya.fr",
    316: "Parent isolé : toutes les aides disponibles — ASF, RSA majoré, réductions. Guide complet sur Economya.fr",
    317: "Études supérieures des enfants : épargner tôt — 50€/mois pendant 18 ans. Guide complet sur Economya.fr",
    318: "Pass culture 300€ : utiliser intelligemment — Concerts, livres, formations. Guide complet sur Economya.fr",
    319: "Poussette d'occasion : ce qu'il faut vérifier — Poussette à -70%. Guide complet sur Economya.fr",
    320: "Jeux éducatifs gratuits pour enfants — Apprendre en jouant à 0€. Guide complet sur Economya.fr",
    321: "Réduire sa facture d'énergie en hiver — Jusqu'à 400€ économisés. Guide complet sur Economya.fr",
    322: "Pompe à chaleur : aides et rentabilité 2025 — MaPrimeRénov' jusqu'à 11 000€. Guide complet sur Economya.fr",
    323: "Isolation des combles : coût et subventions — Isolation à 1€ possible. Guide complet sur Economya.fr",
    324: "Véhicule électrique : vrai coût vs essence sur 5 ans — 3 000€ économisés/an. Guide complet sur Economya.fr",
    325: "Bonus réparabilité : liste des appareils concernés — Jusqu'à 45€ par réparation. Guide complet sur Economya.fr",
    326: "Slow fashion : consommer mieux et moins — Mode durable sans se ruiner. Guide complet sur Economya.fr",
    327: "Alimentation durable sans se ruiner — Local, bio, pas cher. Guide complet sur Economya.fr",
    328: "Économiser l'eau au quotidien — -30% sur la facture eau. Guide complet sur Economya.fr",
    329: "Bilan carbone personnel : comment le réduire — Moins de gaz = moins de charges. Guide complet sur Economya.fr",
    330: "Compostage urbain : guide pratique débutant — Engrais gratuit pour le jardin. Guide complet sur Economya.fr",
    331: "Chaudière à granulés : prix et subventions — Jusqu'à 10 000€ d'aide. Guide complet sur Economya.fr",
    332: "Empreinte numérique : réduire et économiser — Moins de data = moins cher. Guide complet sur Economya.fr",
    333: "Textile recyclé : où acheter vraiment moins cher — Friperies et sites recommandés. Guide complet sur Economya.fr",
    334: "Achat groupé de panneaux solaires — -20% via groupement. Guide complet sur Economya.fr",
    335: "Communauté énergétique locale : comment rejoindre — Électricité moins chère ensemble. Guide complet sur Economya.fr",
    336: "ETF World : comment investir simplement — Le placement préféré des riches. Guide complet sur Economya.fr",
    337: "Livret A vs LEP vs LDDS : que choisir en 2025 — LEP à 4% : ouvrez-le. Guide complet sur Economya.fr",
    338: "Ouvrir son premier PEA : démarche et premiers achats — Commencez avec 50€. Guide complet sur Economya.fr",
    339: "PEA : ouvrir, gérer, optimiser — 0% d'impôt après 5 ans. Guide complet sur Economya.fr",
    340: "Fonds euros vs unités de compte : arbitrer intelligemment — 152 500€ transmis sans impôts. Guide complet sur Economya.fr",
    341: "SCPI : guide complet 2025 — Immobilier dès 200€. Guide complet sur Economya.fr",
    342: "Investir 100€/mois en Bourse : simulation sur 20 ans — 100€/mois = 41 000€ en 20 ans. Guide complet sur Economya.fr",
    343: "DCA : stratégie d'investissement régulier — Investir sans stress de marché. Guide complet sur Economya.fr",
    344: "Bitcoin en 2025 : acheter, stocker, sécuriser — Guide sans jargon. Guide complet sur Economya.fr",
    345: "Or physique : acheter et stocker en France — Valeur refuge accessible. Guide complet sur Economya.fr",
    346: "Immeuble de rapport : premier achat à petit budget — Rendement 8–12% possible. Guide complet sur Economya.fr",
    347: "Colocation investisseur : maximiser le rendement — +3% de rendement vs location simple. Guide complet sur Economya.fr",
    348: "Airbnb vs Booking : quelle plateforme choisir pour louer — Le vrai calcul avant de se lancer. Guide complet sur Economya.fr",
    349: "Location saisonnière : cadre légal 2025 — Évitez les amendes. Guide complet sur Economya.fr",
    350: "Parkings et caves : petits investissements rentables — Rendement 7–10% avec peu d'effort. Guide complet sur Economya.fr",
    351: "CPF 2025 : ce qu'on peut encore financer — Jusqu'à 5 000€ disponibles. Guide complet sur Economya.fr",
    352: "Formation professionnelle gratuite : toutes les options — Se former sans débourser. Guide complet sur Economya.fr",
    353: "MOOC gratuits : les 20 meilleurs — Harvard, MIT, Polytechnique gratuit. Guide complet sur Economya.fr",
    354: "Apprendre à coder gratuitement : parcours complet — Développeur sans école à 10 000€. Guide complet sur Economya.fr",
    355: "YouTube pour apprendre : les chaînes sérieuses — Expertise gratuite sur tous les sujets. Guide complet sur Economya.fr",
    356: "Certifications gratuites reconnues : Google, Meta, IBM — CV boosté sans frais. Guide complet sur Economya.fr",
    357: "Apprentissage : avantages financiers pour l'apprenti — Salaire + diplôme = combo gagnant. Guide complet sur Economya.fr",
    358: "VAE : obtenir un diplôme par son expérience — Diplômé sans reprendre les cours. Guide complet sur Economya.fr",
    359: "Bac pro vs BTS vs BUT : que choisir — Quel parcours pour quel salaire. Guide complet sur Economya.fr",
    360: "Erasmus+ : toutes les bourses disponibles — Jusqu'à 700€/mois pour étudier à l'étranger. Guide complet sur Economya.fr",
    361: "Master à l'étranger : financer son projet — Master gratuit en Allemagne. Guide complet sur Economya.fr",
    362: "Bootcamp coding : rentabilité et alternatives — ROI en moins de 6 mois. Guide complet sur Economya.fr",
    363: "Micro-learning : apprendre 15 min par jour — Compétence en 3 mois. Guide complet sur Economya.fr",
    364: "AFPA : formations financées pour demandeurs d'emploi — Financement 100% possible. Guide complet sur Economya.fr",
    365: "Cours en ligne payants vs gratuits : quand payer — Ne payez que ce qui vaut le coup. Guide complet sur Economya.fr",
    366: "APL 2025 : calcul et demande à la CAF — Jusqu'à 400€/mois d'aide. Guide complet sur Economya.fr",
    367: "RSA : conditions et démarches en 2025 — Jusqu'à 635€/mois. Guide complet sur Economya.fr",
    368: "Prime d'activité : simulation et demande — Jusqu'à 300€/mois en plus. Guide complet sur Economya.fr",
    369: "Aides sociales non demandées : 6 Mds€ non réclamés — Réclamez ce qui vous est dû. Guide complet sur Economya.fr",
    370: "Aide alimentaire : toutes les ressources en France — Banques alimentaires et épiceries sociales. Guide complet sur Economya.fr",
    371: "Surendettement : procédure et sortie de crise — Commission Banque de France. Guide complet sur Economya.fr",
    372: "Crédit à la consommation : les pièges et alternatives — Évitez les taux à 20%. Guide complet sur Economya.fr",
    373: "Rachat de crédit : quand c'est vraiment utile — Mensualités réduites de 30%. Guide complet sur Economya.fr",
    374: "Budget zéro basé : méthode et application — Chaque euro a un rôle. Guide complet sur Economya.fr",
    375: "Méthode 50/30/20 : appliquer concrètement — Budget automatique en 3 enveloppes. Guide complet sur Economya.fr",
    376: "YNAB vs Bankin vs Linxo : quel outil budget choisir — Gérez vos finances comme un pro. Guide complet sur Economya.fr",
    377: "Couple et argent : gérer les finances à deux — Sans disputes, avec clarté. Guide complet sur Economya.fr",
    378: "Divorce et argent : protéger son patrimoine — Anticipez les conséquences. Guide complet sur Economya.fr",
    379: "Finances après séparation : repartir de zéro — Guide de reconstruction. Guide complet sur Economya.fr",
    380: "Ados et argent de poche : apprendre à gérer — Les bases de la gestion dès 12 ans. Guide complet sur Economya.fr",
    381: "Anxiété financière : reconnaître et surmonter — Reprendre le contrôle. Guide complet sur Economya.fr",
    382: "TDAH et budget : gérer ses finances autrement — Systèmes adaptés au TDAH. Guide complet sur Economya.fr",
    383: "Inflation 2025 : s'adapter et protéger son pouvoir d'achat — Vos stratégies anti-inflation. Guide complet sur Economya.fr",
    384: "Femmes et argent : rattraper son retard — Retraite, investissement, salaire. Guide complet sur Economya.fr",
    385: "Expatriation : optimiser ses finances à l'étranger — Fiscalité avantageuse. Guide complet sur Economya.fr",
    386: "Retraite à l'étranger : les pays les moins chers — Retraite confortable avec 1 200€/mois. Guide complet sur Economya.fr",
    387: "Désencombrement rentable : transformer ses placards en cash — 1 000€ dans vos placards. Guide complet sur Economya.fr",
    388: "Consommation consciente : acheter moins et mieux — Qualité vs quantité. Guide complet sur Economya.fr",
    389: "Vivre avec 1 000€/mois : méthodes et témoignages — C'est possible, voici comment. Guide complet sur Economya.fr",
    390: "Burn-out : récupérer sans se ruiner — Se soigner sans s'endetter. Guide complet sur Economya.fr",
    391: "Accompagnement psy sans se ruiner : MonPsy, Nightline, pairs — Thérapie dès 15€ la séance. Guide complet sur Economya.fr",
    392: "Cohérence cardiaque et pleine conscience : apps et méthodes gratuites — Zéro stress, zéro dépense. Guide complet sur Economya.fr",
    393: "Strava, Garmin, Polar : tracker son sport sans abonnement — Musculaire, cardio, yoga à 0€. Guide complet sur Economya.fr",
    394: "Jeûne intermittent : bénéfices santé et économies — -20% sur les courses alimentaires. Guide complet sur Economya.fr",
    395: "Slow living : ralentir pour dépenser moins — La sobriété comme choix. Guide complet sur Economya.fr",
    396: "Tiny house en France : construire ou acheter — Logement dès 30 000€. Guide complet sur Economya.fr",
    397: "Aménager son van : guide budget et matériaux — 800€/mois tout compris. Guide complet sur Economya.fr",
    398: "Bali, Tbilissi, Lisbonne : les meilleures bases pour nomades — Travailler depuis le monde entier. Guide complet sur Economya.fr",
    399: "Ruralité choisie : économiser en quittant la ville — Loyer divisé par 3. Guide complet sur Economya.fr",
    400: "Permaculture et autonomie alimentaire — Légumes gratuits toute l'année. Guide complet sur Economya.fr",
    401: "Maison passive : coûts et économies sur 20 ans — Facture chauffage proche de 0€. Guide complet sur Economya.fr",
    402: "Chèques vacances : utilisation maximale — Jusqu'à 600€ d'aides loisirs. Guide complet sur Economya.fr",
    403: "Musées gratuits : tous les jours et horaires — Louvre, Orsay : gratuit les soirs. Guide complet sur Economya.fr",
    404: "Sorties culturelles à prix réduit : carte jeune — -50% cinéma, théâtre, concerts. Guide complet sur Economya.fr",
    405: "Repair café : réparer au lieu d'acheter — Réparer gratuitement avec des experts. Guide complet sur Economya.fr",
    406: "Bibliothèque d'objets : emprunter au lieu d'acheter — Perceuse, tente, vélo à 0€. Guide complet sur Economya.fr",
    407: "Soldes : comment acheter vraiment moins cher — Les vraies bonnes affaires. Guide complet sur Economya.fr",
    408: "Cyber Monday et ventes flash : les vraies fenêtres d'achat — Les prix vraiment en baisse. Guide complet sur Economya.fr",
    409: "Cashback cumulé : comment empiler cartes, extensions et apps — Jusqu'à 2% remboursé sur vos achats. Guide complet sur Economya.fr",
    410: "Néobanques 2025 : le comparatif complet — Zéro frais, cashback, assurances. Guide complet sur Economya.fr",
    411: "Cartes Amex, Visa : accumuler des miles en France — Voyages offerts par votre carte. Guide complet sur Economya.fr",
    412: "Garanties légales acheteur : droits et procédures — 2 ans de garantie minimum. Guide complet sur Economya.fr",
    413: "Arnaques en ligne : reconnaître et signaler — Protégez vos économies. Guide complet sur Economya.fr",
    414: "Identité numérique volée : que faire — Réagir vite pour éviter le pire. Guide complet sur Economya.fr",
    415: "Grenier en or : évaluer et vendre ses objets — Des centaines d'€ dans vos tiroirs. Guide complet sur Economya.fr",
    416: "Vendre ses créations en ligne : plateformes gratuites — Etsy, Fiverr, Redbubble. Guide complet sur Economya.fr",
    417: "Tutorat en ligne : devenir prof et gagner sa vie — 30–50€/h en enseignant. Guide complet sur Economya.fr",
    418: "Moonlighting : avoir un 2e revenu légal — +500 à +2 000€/mois. Guide complet sur Economya.fr",
    419: "Location de sa résidence principale : règles et revenus — Règles et optimisation fiscale. Guide complet sur Economya.fr",
    420: "Fiverr et Malt : trouver ses premiers clients freelance — Premiers revenus en 2 semaines. Guide complet sur Economya.fr",
    421: "Side hustle : 20 idées testées en France — Trouvez votre 2e source de revenus. Guide complet sur Economya.fr",
    422: "Revenus passifs réels : ce qui marche vraiment — Gagner pendant qu'on dort. Guide complet sur Economya.fr",
    423: "Affiliation en ligne : démarrer gratuitement — Commissions sans créer de produit. Guide complet sur Economya.fr",
    424: "Newsletter payante : monétiser son expertise — 1 000 abonnés = 1 000€/mois. Guide complet sur Economya.fr",
    425: "Vendre sur Vinted : optimiser ses revenus — 500 à 2 000€ dans vos armoires. Guide complet sur Economya.fr",
    426: "Leboncoin : vendre plus vite et plus cher — Astuces pour doubler vos prix. Guide complet sur Economya.fr",
    427: "Amazon FBA en 2025 : encore rentable ? — Le vrai calcul de rentabilité. Guide complet sur Economya.fr",
    428: "E-commerce : lancer une boutique pour 0€ — Shopify, Etsy, sans capital. Guide complet sur Economya.fr",
    429: "Dropshipping en 2025 : est-ce encore rentable ? — La vérité sans bullshit. Guide complet sur Economya.fr",
    430: "Seuils de revenus : impôts et aides en 2025 — Ne dépassez pas les plafonds clés. Guide complet sur Economya.fr",
    431: "Niches fiscales méconnues : les 10 meilleures — Jusqu'à 10 000€ de réduction d'impôt. Guide complet sur Economya.fr",
    432: "Don aux associations : déduction fiscale — 66% déduit de votre impôt. Guide complet sur Economya.fr",
    433: "Déclaration de revenus 2025 : cases méconnues — Cases que personne ne coche. Guide complet sur Economya.fr",
    434: "Avis d'imposition : le décrypter complètement — Vérifiez chaque chiffre. Guide complet sur Economya.fr",
    435: "Remboursement d'impôt : comment l'accélérer — Récupérez votre trop-perçu. Guide complet sur Economya.fr",
    436: "Contrôle fiscal : droits du contribuable — Comment se défendre. Guide complet sur Economya.fr",
    437: "Dividendes : comprendre la flat tax — Optimiser ses revenus boursiers. Guide complet sur Economya.fr",
    438: "Plus-value immobilière : calcul et exonérations — Exonérations méconnues. Guide complet sur Economya.fr",
    439: "PER collectif vs individuel : que choisir — Quel plan retraite est le meilleur. Guide complet sur Economya.fr",
    440: "Épargne salariale : les pièges à éviter — Ne laissez pas dormir vos primes. Guide complet sur Economya.fr",
    441: "Défiscalisation immobilière : loi Denormandie 2025 — -21% d'impôt sur 12 ans. Guide complet sur Economya.fr",
    442: "Auto-entrepreneur : charges, cotisations, simulation — Ce qu'il vous reste vraiment. Guide complet sur Economya.fr",
    443: "Financer sa création d'entreprise à 0€ — ACRE, ARCE, subventions. Guide complet sur Economya.fr",
    444: "Fichier FICP : en sortir plus vite — Retrouver sa liberté financière. Guide complet sur Economya.fr",
    445: "Scoring bancaire : comment l'améliorer — Accéder aux meilleurs taux. Guide complet sur Economya.fr",
    446: "Banque en ligne pour interdit bancaire — Compte garanti même en difficultés. Guide complet sur Economya.fr",
    447: "Matelas de sécurité : le calculer et le constituer en 6 mois — 3 mois de charges en réserve. Guide complet sur Economya.fr",
    448: "Urgences financières : le plan de survie — Que faire quand tout s'effondre. Guide complet sur Economya.fr",
    449: "Ciclade : rechercher un contrat d'assurance-vie oublié — Des millions non réclamés chaque an. Guide complet sur Economya.fr",
    450: "Retraites complémentaires : retrouver des droits perdus — Vérifiez votre relevé de carrière. Guide complet sur Economya.fr",
    451: "Comptes dormants : procédure pour récupérer son dû à la Caisse — Cherchez dans la base FICOBA. Guide complet sur Economya.fr",
    452: "Testament : l'écrire soi-même légalement — Sans notaire, 100% valide. Guide complet sur Economya.fr",
    453: "SCPI papier-pierre : investir à partir de 200€ — Immobilier sans gestion. Guide complet sur Economya.fr",
    454: "Indépendance financière à 40 ans : le plan chiffré — Retraite à 45 ans, c'est possible. Guide complet sur Economya.fr",
    455: "Retraite à 50 ans : est-ce possible en France ? — Les conditions et le plan. Guide complet sur Economya.fr",
    456: "Habitudes des gens riches : ce que dit la science — Adoptez les bons réflexes. Guide complet sur Economya.fr",
    457: "Psychologie de l'argent : les biais cognitifs — Arrêtez de vous saboter. Guide complet sur Economya.fr",
    458: "Livres incontournables sur la finance personnelle — Les 10 livres qui changent tout. Guide complet sur Economya.fr",
    459: "Chaînes YouTube finance : les meilleures en français — Apprendre la finance gratuitement. Guide complet sur Economya.fr",
    460: "Podcasts finances personnelles : les meilleurs en 2025 — S'enrichir en écoutant. Guide complet sur Economya.fr",
    461: "Simulateur retraite : anticiper avec précision — Calculez votre future pension. Guide complet sur Economya.fr",
    462: "Bilan patrimonial gratuit : comment le faire soi-même — Connaître sa situation nette. Guide complet sur Economya.fr",
    463: "Objectif financier : comment le poser et l'atteindre — SMART goals financiers. Guide complet sur Economya.fr",
    464: "Désencombrement : méthode KonMari et revenus — 500 à 2 000€ en désencombrant. Guide complet sur Economya.fr",
    465: "Coliving : vivre en communauté, réduire les coûts — Loyer partagé, vie sociale offerte. Guide complet sur Economya.fr",
    466: "Négociation salariale : scripts et psychologie — Les mots exacts qui fonctionnent. Guide complet sur Economya.fr",
    467: "Vendre des formations en ligne : outils gratuits — Monétisez votre expertise. Guide complet sur Economya.fr",
    468: "Podcaster et monétiser : guide débutant complet — Premiers revenus en 6 mois. Guide complet sur Economya.fr",
    469: "Print on demand : créer sans stock ni capital — T-shirts, livres, objets sans frais. Guide complet sur Economya.fr",
    470: "Troc et échanges de services : plateformes actives — Obtenir sans dépenser. Guide complet sur Economya.fr",
    471: "Coopératives d'achats : rejoindre et économiser — -20 à -40% sur votre panier. Guide complet sur Economya.fr",
    472: "Habitat participatif : acheter en commun — Propriétaire pour moins cher. Guide complet sur Economya.fr",
    473: "Groupement forestier d'investissement (GFI) : rendement et fiscalité — Réduction d'impôt et rendement. Guide complet sur Economya.fr",
    474: "Crowdfunding immobilier : risques et rendements réels — 8–12% de rendement potentiel. Guide complet sur Economya.fr",
    475: "Reconversion agricole : aides et réalité du métier — JA, DJA et dotations à l'installation. Guide complet sur Economya.fr",
    476: "Vieilles Charrues, Hellfest, Rock en Seine : devenir bénévole — Accès gratuit + repas + camping. Guide complet sur Economya.fr",
    477: "Réductions jeunes et étudiants pour le spectacle vivant — Places à 5€ dans les grandes salles. Guide complet sur Economya.fr",
    478: "Bretagne, Occitanie, Auvergne : week-ends France pas chers — Week-end complet dès 80€. Guide complet sur Economya.fr",
    479: "Bénévolat à l'international : partir gratuitement — Voyage pris en charge. Guide complet sur Economya.fr",
    480: "Hospitality exchange : Couchsurfing et alternatives — Hébergement gratuit partout. Guide complet sur Economya.fr",
    481: "Argent et bonheur : ce que dit la science — Le seuil au-delà duquel ça ne change rien. Guide complet sur Economya.fr",
    482: "Monnaie locale : utiliser et en bénéficier — Bonus de 5 à 10%. Guide complet sur Economya.fr",
    483: "Micro-BIC vs BNC : quel régime choisir — Optimisez votre statut. Guide complet sur Economya.fr",
    484: "ACRE : exonération de cotisations à la création — 50% de cotisations en moins. Guide complet sur Economya.fr",
    485: "Médiation bancaire : quand et comment y recourir — Gratuit et souvent efficace. Guide complet sur Economya.fr",
    486: "Négociation avec les créanciers : méthode complète — Réduire ses dettes légalement. Guide complet sur Economya.fr",
    487: "Microcrédit : accéder au financement sans banque — Jusqu'à 12 000€ via l'Adie. Guide complet sur Economya.fr",
    488: "Droit à l'oubli bancaire : après un surendettement — Repartir sur de bonnes bases. Guide complet sur Economya.fr",
    489: "BPI France : aides aux entrepreneurs — Prêts, garanties, subventions. Guide complet sur Economya.fr",
    490: "Aides régionales : trouver celles disponibles — Des milliers € selon votre région. Guide complet sur Economya.fr",
    491: "Carte Mastercard World Elite gratuite : comment l'obtenir — Assurances et avantages premium. Guide complet sur Economya.fr",
    492: "Revolut, N26, Lydia : quelle néobanque en 2025 — Zéro frais, cashback, lounge. Guide complet sur Economya.fr",
    493: "Caisse des Dépôts : retrouver les avoirs bancaires oubliés — Cherchez votre argent oublié. Guide complet sur Economya.fr",
    494: "Work and travel : travailler en voyageant légalement — Se financer en voyageant. Guide complet sur Economya.fr",
    495: "Taux d'épargne de 50% : comment y arriver concrètement — La méthode complète pas à pas. Guide complet sur Economya.fr",
    496: "Actions françaises à dividende : sélection 2025 — 5 à 8% de rendement annuel. Guide complet sur Economya.fr",
    497: "Défiscalisation : toutes les niches légales 2025 — Réduisez votre impôt de 30%. Guide complet sur Economya.fr",
    498: "Assurance rapatriement : quand est-elle vraiment utile — Votre carte bleue vous couvre peut-être. Guide complet sur Economya.fr",
    499: "L'avenir de l'économie frugale : tendances 2025–2030 — Ce qui va changer pour vos finances. Guide complet sur Economya.fr",
    500: "500 articles : ce qu'on a vraiment appris sur l'argent — Le grand bilan final. Guide complet sur Economya.fr",
}

dossier = os.path.dirname(os.path.abspath(__file__))
modifies = 0
deja = 0
non_trouves = 0

for num, description in DESCRIPTIONS.items():
    filepath = os.path.join(dossier, f'article-{num}.html')
    if not os.path.exists(filepath):
        non_trouves += 1
        continue
    
    with open(filepath, 'r', encoding='utf-8') as f:
        html = f.read()
    
    if 'name="description"' in html:
        deja += 1
        continue
    
    meta_tag = f'''<meta name="description" content="{description}">\n'''
    html_new = html.replace('<meta charset="UTF-8">', f'''<meta charset="UTF-8">\n{meta_tag}''', 1)
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(html_new)
    modifies += 1

print(f"✅ {modifies} articles mis à jour avec balises meta SEO")
print(f"ℹ️  {deja} articles avaient déjà une meta description")
print(f"ℹ️  {non_trouves} fichiers non trouvés")
input("\nAppuyez sur Entrée pour fermer...")
